name: Quarto Publish (R & Custom Packages)
on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy pandas matplotlib polars statsmodels
        # 추가로 필요한 패키지 설치

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R Packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(c("reticulate", "knitr", "rmarkdown", "tidyverse", "NHANES", "ggplot2", "broom", "dplyr", "forcats"))
        # 추가로 필요한 패키지 설치
        shell: Rscript {0}

      - name: Render Quarto
        run: |
          export RETICULATE_PYTHON=$(python -c "import sys; print(sys.executable)")
          python -c "import pyexpat, pandas, statsmodels.api; print('Python:', __import__('sys').executable); print('Expat:', pyexpat.EXPAT_VERSION)"
          Rscript -e 'library(reticulate); use_python(Sys.getenv("RETICULATE_PYTHON"), required = TRUE); py_run_string("import pyexpat, pandas, statsmodels.api as sm\nprint(\"reticulate expat:\", pyexpat.EXPAT_VERSION)")'
          quarto render
        shell: bash -l {0}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
